/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarreiraRouteImport } from './routes/carreira'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as GolsRouteImport } from './routes/gols'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as MelhoresGolsRouteImport } from './routes/melhores-gols'
import { Route as TitulosRouteImport } from './routes/titulos'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ClubeSlugRouteImport } from './routes/clube.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreiraRoute = CarreiraRouteImport.update({
  id: '/carreira',
  path: '/carreira',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const GolsRoute = GolsRouteImport.update({
  id: '/gols',
  path: '/gols',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const MelhoresGolsRoute = MelhoresGolsRouteImport.update({
  id: '/melhores-gols',
  path: '/melhores-gols',
  getParentRoute: () => rootRouteImport,
} as any)
const TitulosRoute = TitulosRouteImport.update({
  id: '/titulos',
  path: '/titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubeSlugRoute = ClubeSlugRouteImport.update({
  id: '/clube/$slug',
  path: '/clube/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/estatisticas': typeof EstatisticasRoute
  '/galeria': typeof GaleriaRoute
  '/gols': typeof GolsRoute
  '/historia': typeof HistoriaRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/melhores-gols': typeof MelhoresGolsRoute
  '/titulos': typeof TitulosRoute
  '/videos': typeof VideosRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/estatisticas': typeof EstatisticasRoute
  '/galeria': typeof GaleriaRoute
  '/gols': typeof GolsRoute
  '/historia': typeof HistoriaRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/melhores-gols': typeof MelhoresGolsRoute
  '/titulos': typeof TitulosRoute
  '/videos': typeof VideosRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carreira': typeof CarreiraRoute
  '/estatisticas': typeof EstatisticasRoute
  '/galeria': typeof GaleriaRoute
  '/gols': typeof GolsRoute
  '/historia': typeof HistoriaRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/melhores-gols': typeof MelhoresGolsRoute
  '/titulos': typeof TitulosRoute
  '/videos': typeof VideosRoute
  '/clube/$slug': typeof ClubeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carreira'
    | '/estatisticas'
    | '/galeria'
    | '/gols'
    | '/historia'
    | '/linha-do-tempo'
    | '/melhores-gols'
    | '/titulos'
    | '/videos'
    | '/clube/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carreira'
    | '/estatisticas'
    | '/galeria'
    | '/gols'
    | '/historia'
    | '/linha-do-tempo'
    | '/melhores-gols'
    | '/titulos'
    | '/videos'
    | '/clube/$slug'
  id:
    | '__root__'
    | '/'
    | '/carreira'
    | '/estatisticas'
    | '/galeria'
    | '/gols'
    | '/historia'
    | '/linha-do-tempo'
    | '/melhores-gols'
    | '/titulos'
    | '/videos'
    | '/clube/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarreiraRoute: typeof CarreiraRoute
  EstatisticasRoute: typeof EstatisticasRoute
  GaleriaRoute: typeof GaleriaRoute
  GolsRoute: typeof GolsRoute
  HistoriaRoute: typeof HistoriaRoute
  LinhaDoTempoRoute: typeof LinhaDoTempoRoute
  MelhoresGolsRoute: typeof MelhoresGolsRoute
  TitulosRoute: typeof TitulosRoute
  VideosRoute: typeof VideosRoute
  ClubeSlugRoute: typeof ClubeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreira': {
      id: '/carreira'
      path: '/carreira'
      fullPath: '/carreira'
      preLoaderRoute: typeof CarreiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gols': {
      id: '/gols'
      path: '/gols'
      fullPath: '/gols'
      preLoaderRoute: typeof GolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melhores-gols': {
      id: '/melhores-gols'
      path: '/melhores-gols'
      fullPath: '/melhores-gols'
      preLoaderRoute: typeof MelhoresGolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titulos': {
      id: '/titulos'
      path: '/titulos'
      fullPath: '/titulos'
      preLoaderRoute: typeof TitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clube/$slug': {
      id: '/clube/$slug'
      path: '/clube/$slug'
      fullPath: '/clube/$slug'
      preLoaderRoute: typeof ClubeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarreiraRoute: CarreiraRoute,
  EstatisticasRoute: EstatisticasRoute,
  GaleriaRoute: GaleriaRoute,
  GolsRoute: GolsRoute,
  HistoriaRoute: HistoriaRoute,
  LinhaDoTempoRoute: LinhaDoTempoRoute,
  MelhoresGolsRoute: MelhoresGolsRoute,
  TitulosRoute: TitulosRoute,
  VideosRoute: VideosRoute,
  ClubeSlugRoute: ClubeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
